config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'homes/show'

  #this is a much better way of serving static pages through the show controller
  get 'static_pages/*page' => 'static_pages#show'
  devise_for :admins
  resources :blogs

   # resources :homes, only: [:show]
  # root to: "homes#show"

  resources :messages, only: [:new, :create]
  get 'messages/new'

  resources :newsletters


  root 'static_pages#show', page: 'home'

  get 'public/*page' =>'static_pages#download'
 # Error pages routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: :true

  has_many :blogs, dependent: :destroy
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :admin
  has_permalink
  validates_presence_of :title

  validates_presence_of :blog_content

end

app/models/message.rb
class Message
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations
  attr_accessor :name, :email, :subject, :content
  validates :name, :email, :subject, :content, presence: true
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :email,:name,:telephone, presence: true
  validates :email,:telephone, :uniqueness => {:message => 'One of the fields has already submitted in the database'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    #this has changed from for to permit for rails 4 onwards
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update,keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]

   before_filter :authenticate_admin!, only: [:new,:create,:edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index

     @blogs = Blog.paginate(:page => params[:page],:per_page => 2).order("created_at DESC")
      pry
     #@users = User.paginate(:page => params[:page], :per_page => 5)
    # @blogs = Blog.where(admin: current_admin).order("created_at DESC")
    # @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
      # binding.pry
    @blog = Blog.find_by_permalink(params[:id])

  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.admin_id = current_admin.id
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:blog_content, :title)
    end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    #your_new_after_confirmation_path
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found

  	render(status: 404)
  end

  def internal_server_error
  	render(status: 500)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end
  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.message_me(@message).deliver_now
      redirect_to new_message_path, notice: "Thank you for your message."
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :subject, :content)
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  #layout 'static_pages/home.html.erb'
  def new
    @trainee = Newsletter.new
  end

  def create
    @trainee = Newsletter.new(trainee_params)
    if @trainee.save
      # Deliver the signup email
      MessageMailer.send_signup_email(@trainee).deliver_now
      redirect_to root_path, notice: 'Credentials were submitted and a welcome email has been sent to your email address'
    else
      redirect_to root_path, notice: 'Credentials were not submitted- one of the fields has already been submitted-either telephone or email.'

    end

  end
 
  private
  def trainee_params
    params.require(:newsletter).permit(:email,:name,:telephone)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if valid_page?
      render template: "static_pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end
  def download
      send_file(
          "#{Rails.root}/public/write_up_v1.pdf",
          filename: "TheRailsShopCurriculum.pdf",
          type: "application/pdf"
      )
  end

  private
  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/static_pages/#{params[:page]}.html.erb"))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true,
                                  :hard_wrap => true)
    options = {
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :autolink => true,
        :lax_html_blocks => true,
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg)}.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
		<div class="alert alert-danger alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times; </button>
		<h4>#{sentence}</h4>
		#{messages}
		</div>
    HTML

    html.html_safe
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= form_for(@blog) do |f| %>
          <% if @blog.errors.any? %>
              <div id="error_explanation"class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

                <ul>
                  <% @blog.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="form-group">
            <%= f.label :title%>
            <%= f.text_field :title, class: "form-control"%>
            <%= f.label :blog_content %><br>
            <%= f.text_area :blog_content, class: "form-control" %>
          </div>

          <div class="actions">
            <%= f.submit class:'btn btn-primary' %>
          </div>
      <% end %>

    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 ">
      <h1 id="blog-edit">Editing Blog</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @blog %> |
      <%= link_to 'Back', blogs_path %>

    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="inner-page-banner" style="background-image: url('/assets/blog-header.jpg');">
        <div class="opacity" style="padding-bottom: 38px;">
          <h1>You just have to  wing it<br> before you kill it.</h1>
          <br><br>
          <p style="color: white; line-height: 26px;">“Successful people are really, really good at making things up as they go. They excel <br>at reacting to reality, rather than working within the confines of a rigid plan.”
— Ken Mazaika
</p>
        </div> <!-- /.opacity -->
      </div> <!-- /inner-page-banner -->


<p id="notice"><%= notice %></p>
<div class="container">
  <article>
    <div class="row">
      <div class="blog">
        <%@blogs.each do |blog|%>
              <!--<h2>Blog Post title</h2>-->
              <div class=" author-image col-xs-2 col-xs-offset-5 col-sm-2 col-sm-offset-5">
                <%=gravatar_image_tag(blog.admin.email, class:'img-circle img-responsive', :alt => 'alex shyaka')%>
              </div>
              <div class=" author-text col-xs-8 col-xs-offset-4 col-md-3 col-md-offset-5">
                <h4><%= blog.admin.name%></h4>
                <p>Founder TheRailsShop.</p>
                <cite><strong>Wing it till you make it</strong></cite>
              </div>

            </div>
      </div>
            <div class="row">
                <div class="blog">
                    <div class="blog-title col-sm-12 col-md-8 col-md-offset-2"><h2><%= blog.title%></h2></div>
        <!--            <div class="row">-->
                      <div class=" posted-date  col-md-8 col-xs-12 col-md-offset-2">
                        <small>Posted <%= time_ago_in_words(blog.created_at)%> ago</small>
                      </div>
        <!--            </div>-->


                    <div class="post-body col-sm-8 col-sm-offset-2">
                      <p><%=  markdown(truncate(blog.blog_content,length: 160))%></p>
                      <p><%= link_to 'read more', blog_path(blog) %></p>
                    </div>
                    <div class="post-footer col-sm-8 col-sm-offset-2">
                      <cite>Crafted by <%= blog.admin.name%></cite>
                      <hr>
                    </div>
                    <%if (signed_in?)&& (current_admin.email=='shyakaster@gmail.com' or current_admin.email=='mbandashyaka@gmail.com') %>
                        <div class="col-sm-8 col-sm-offset-2"><p><%= link_to 'New Blog', new_blog_path %></p></div>
                    <%end%>
                    <div class="will-paginate col-sm-8 col-sm-offset-2"><%= will_paginate @blogs %></div>
                <%end%>

      </div>

    </div>

  </article>

</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h1 id="new-blog">New Blog</h1>

      <%= render 'form' %>

      <%= link_to 'Back', blogs_path %>

    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="inner-page-banner" style="background-image: url('/assets/blog-header.jpg');">
        <div class="opacity" style="padding-bottom: 38px;">
          <h1>You just have to  wing it<br> before you kill it.</h1>
          <br><br>
          <p style="color: white; line-height: 26px;">“Successful people are really, really good at making things up as they go. They excel <br>at reacting to reality, rather than working within the confines of a rigid plan.”
— Ken Mazaika
</p>
        </div> <!-- /.opacity -->
      </div> <!-- /inner-page-banner -->
<div class="container">
  <article>

    <div class="row">
      <!--<h2>Blog Post title</h2>-->
      <div class=" author-image col-xs-2 col-xs-offset-5 col-sm-2 col-sm-offset-5">
        <%=gravatar_image_tag(@blog.admin.email, class:'img-circle img-responsive', :alt => 'alex shyaka')%>
      </div>
      <div class=" author-text col-xs-8 col-xs-offset-4 col-md-3 col-md-offset-5">
        <h4><%= @blog.admin.name%></h4>
        <p>Founder TheRailsShop.</p>
        <cite><strong>Wing it till you make it</strong></cite>
      </div>
    </div>

    <div class="row">
      <div class="blog">
            <div class="blog-title col-sm-12 col-md-8 col-md-offset-2">
              <h2><%= @blog.title%></h2>
            </div>
            <div class=" posted-date  col-md-8 col-xs-12 col-md-offset-2">
              <small>Posted <%= time_ago_in_words(@blog.created_at)%> ago</small>
            </div>

            <div class="post-body col-sm-8 col-sm-offset-2">
              <p><%= markdown(@blog.blog_content)%></p>
            </div>
            <div class="post-footer col-sm-8 col-sm-offset-2">
              <cite>Crafted by <%= @blog.admin.name%></cite>
              <hr>
            </div>
        <div class="row">
          <div class="back-to-list col-sm-4 col-sm-offset-2"><p><%= link_to 'Back to blog list', blogs_path %></p></div>
          <div class="back-to-list col-sm-6">
            <%= awesome_share_buttons(@blog.title) %>
          </div>
        </div>

        <div class="row">
          <div class="disqus">
             <div class="col-sm-8 col-sm-offset-2">
                <!--Disqus code goes here -->
                <%= render 'layouts/partials/disqus'%>
            </div>
          </div>
      </div>
       
    </div>

  </article>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Onsite web development training based in Kampala Uganda with one-on-one mentorship and a customized training program. A chance to join a community of rails developers. Become a full stack web developer">
    <meta name="author" content="nkusi alex shyaka">
    <meta name="google-site-verification" content="08rwRZvkAmiGPqTix8Ws-UL84gdHAQX5MBmC64sKx6g" />
    <!-- <link rel="shortcut icon" href="/assets/favicon.ico)" /> -->
    <link href="<%= image_path("/assets/fav-icon/icon.png") %>" rel="shortcut icon" />
      <!-- font raleway from google.com/fonts-->
      <link href="//fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
      <!-- Font Awesome Icons -->
      <!--<link href="../stylesheets/font-awesome/css/font-awesome.min.css" rel="stylesheet">-->
    <title>The Rails Coding Shop</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
     <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-56596703-2', 'auto');
        ga('send', 'pageview');
        ga('set', 'userId', {{USER_ID}}); // Set the user ID using signed-in user_id.

</script>
<script type="application/ld+json">
  {
  "@context": "http://schema.org",
  "@type": "WebSite",
  "name": "Therailsshop",
  "alternateName": "RailsShop",
  "url": "https://www.therailsshop.club"
}
</script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "https://www.therailsshop.club",
  "contactPoint": [{
    "@type": "ContactPoint",
    "telephone": "+256752969844",
    "contactType": "customer service"
  }]
}
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Person",
  "name": "Therailsshop",
  "url": "https://www.therailsshop.club",
  "sameAs": [
    "http://www.facebook.com/TheRailsShop",
    "http://instagram.com/therailsshop"
  ]
}
</script>
</script>
</head>
<body>

    <%= render 'layouts/partials/header'%>
    <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger"  %> alert-dismissable" >
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times; </button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
        <% end %>
    <% end %>
    <%= yield %>

<%= render 'layouts/partials/signup'%>
<%= render 'layouts/partials/footer'%>



</body>
</html>

app/views/layouts/partials/_defaulthero.html.erb
<!-- FEATURE IMAGE
================================================== -->
<section class="feature-image feature-image-default" data-type="background" data-speed="2">
  <h1></h1>
</section>

app/views/layouts/partials/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = '<%= url_for([@blog,{only_path: false}])%>';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @blog.id%>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//therailsshop.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                

app/views/layouts/partials/_footer.html.erb
<!-- FOOTER
================================================== -->
<footer class="bg-one">
        <div class="container">
          <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="footer-logo">
                <a href="index.html"><img src="/assets/logo/logo.png" alt="Logo"></a>
                <h5><a href="#" class="tran3s">alexshyaka@therailsshop.club</a></h5>
                <h6 class="p-color">+256752969844</h6>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-list">
              <h4>Quick Links</h4>
              <ul>
                <li class="tran3s"><%= link_to "Home", root_path %></li>
                <li><a href="/static_pages/about" class="tran3s">Who We Are</a></li>
                <li><a href="/static_pages/resources" class="tran3s">Resources</a></li>
                <li><a href="/static_pages/our_curriculum" class="tran3s">Our Curriculum</a></li>
                <li><%= link_to "Contact Us", new_message_path %></li>
                <li><%= link_to "Blog", blogs_path %></li>
                
              </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-list">
              <h4>About Us</h4>
              <ul>
                <li><a href="about-us.html" class="tran3s">About The Rails Coding Shop</a></li>
                <li><a href="http://railsgirls.com/uganda.html" class="tran3s">Rails Girls</a></li>
                
              </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-subscribe">
              <h4>Subscribe to our mailing list</h4>
              <form action="#">
                <input type="text" placeholder="Enter your mail">
              </form>
              <ul>
                <li><a href="https://www.facebook.com/TheRailsShop/" class="tran3s"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="https://twitter.com/therailsshop" class="tran3s"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="https://www.instagram.com/therailsshop/" class="tran3s"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                
              </ul>
            </div>
          </div> <!-- /.row -->

          <div class="bottom-footer clearfix" style="color: black;">
            
            <p class="float-left">&copy; 2018 <a href="#" class="tran3s p-color"  style="color: black;">TheRailsShop LTD</a>. Created with <i class="fa fa-heart"></i> by <a href="http://www.samhez.com"  target="_blank"  style="color: black;">Samuel Epodoi</a></p>
          </div>
        </div> <!-- /.container -->
      </footer>


app/views/layouts/partials/_header.html.erb

<header class="theme-menu-wrapper full-width-menu" style="background-color: white; padding-bottom: 20px; -webkit-box-shadow: 0px 3px 17px -1px rgba(0,0,0,0.29);
-moz-box-shadow: 0px 3px 17px -1px rgba(0,0,0,0.29);
box-shadow: 0px 3px 17px -1px rgba(0,0,0,0.29);">
        <div class="header-wrapper">
          <div class="clearfix">
            <!-- Logo -->
            <div class="float-left "><img src="/assets/logo/logo.png" alt="The Rails Shop" style="max-height: 50px; margin-top: -10px;"></div>

            <!-- ============================ Theme Menu ========================= -->
            <nav class="theme-main-menu float-right navbar" id="mega-menu-wrapper">
              <!-- Brand and toggle get grouped for better mobile display -->
               <div class="navbar-header">
                 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                 </button>
               </div>
               <!-- Collect the nav links, forms, and other content for toggling -->
               <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav">
                  <li class=" menu-list"><a href="/" class="tran3s" style="font-size: 15px;" >Home</a>

                  </li>
                  <li class=" menu-list"><a href="/static_pages/about" class="tran3s" style="font-size: 15px;" >About</a>

                  </li>
                  <li class=" menu-list"><a href="/static_pages/our_curriculum" class="tran3s" style="font-size: 15px;" >Our Curriculum</a>

                  </li>
                  <li class=" menu-list"><a href="/" class="tran3s" style="font-size: 15px;" >Events</a>

                  </li>

                  <li class="menu-list"><a href="/static_pages/resources" class="tran3s" style="font-size: 15px;" >Resources</a>

                  </li>
                  <li class="menu-list" style="font-size: 15px;" class="tran3s"><%= link_to "Contact Us", new_message_path %></li>
                  <li class="login-button" style="font-size: 15px;" ><%= link_to "Blog", blogs_path %></li>

                  <% if signed_in?%>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_admin.name%> <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                  <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete%></li>
                                  <li><%= link_to "Edit profile", edit_admin_registration_path%></li>
                                </ul>
                              </li>
                          <%else%>
                              <!--<li>  #link_to "Sign In", #new_admin_session_path %></li>-->
                              <!--<li> #link_to "Sign Up", #new_admin_registration_path %></li>-->
                          <%end%>


                </ul>
               </div><!-- /.navbar-collapse -->
            </nav> <!-- /.theme-main-menu -->
          </div> <!-- /.clearfix -->
        </div>
      </header> <!-- /.theme-menu-wrapper -->

app/views/layouts/partials/_signup.html.erb
<!-- SIGN UP SECTION
 ================================================== -->

<section id="signup" data-type="background" data-speed="4">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h2>Are you ready to take your coding skills to the <strong>next level</strong>?</h2>
        <%=form_for Newsletter.new  do |f| %>
            <div class="signup-form form-group">
              <!--<div class ="input-group-fields">-->
                    <%= f.text_field :name,class: 'form-control input-lg ',placeholder: 'Enter your name in here..'%>
                  <!--</div>-->
                  <div class="input-group-tel">
                    <%= f.text_field :telephone, class: 'form-control input-lg ',placeholder: 'Enter your telephone in here..'%>
                  </div>
                  <!--<input type="text" name="email" class="form-control input-lg" placeholder="Enter your email address in here...">-->
                  <!--<div class="input-group-btn">-->
                    <%= f.email_field :email, class: 'form-control input-lg ',placeholder: 'Enter your email address in here..'%>
              <!--</div>-->
              <div class="input-group-btn">
                                <!--<button class="btn btn-warning btn-lg" type="button">Submit</button>-->
                <%= f.submit value: "Let's get started", class:' btn-success btn-lg'%>
              </div>
            </div>

        <%end%>
      </div>
    </div>
  </div>
</section>

app/views/messages/new.html.erb
<div class="container" style="padding-top: 15%;">
  <div class="row">
    <div class="col-md-4 col-md-offset-2">
        <%= form_for @message do |f| %>
          <% if @message.errors.any? %>
              <div id="error_explanation"class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2><%= pluralize(@message.errors.count, "error") %> prohibited this blog from being saved:</h2>

                <ul>
                  <% @message.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

            <div class=" message-form form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class:'form-control' %>

              <%= f.label :email%>
              <%= f.email_field :email, class:'form-control' %>

              <%= f.label :subject %>
              <%= f.text_field :subject, class:'form-control' %>

              <%= f.label :content %>
              <%= f.text_area :content, class:'form-control' %>
            </div>

            <div class="actions">
              <%= f.submit class: 'btn btn-primary' %>
            </div>
        <% end %>
        </div>
        <section>
            <div class="col-md-4 col-md-offset-2">
           <p class="lead"><img src=/assets/team/1.jpg></p>
            
        </div>
        </section>
        
      </div>
    </div>

app/views/static_pages/contact.html.erb
<%= render 'layouts/partials/defaulthero'%>
<section id="contact_page">
   <p class="lead">We are a web development shop for full stack developers. Rails is our forte!. We are still building out these pages so please be patient with us. We handcraft everything we build so this might take sometime.</p>
</section>

app/views/static_pages/help.html.erb
<section id="help_page">
   <p class="lead">We are a web development shop for full stack developers. Rails is our forte!. We are still building out these pages so please be patient with us. We handcraft everything we build so this might take sometime.</p>
</section>

app/views/static_pages/ourteam.html.erb
<section id="ourteam_page">
   <p class="lead">We are a web development shop for full stack developers. Rails is our forte!. We are still building out these pages so please be patient with us. We handcraft everything we build so this might take sometime. Our current and former students have a lot to say about our training and it will all happen here.</p>
</section>